set(_CATKIN_CURRENT_PACKAGE "geneus")
set(geneus_VERSION "2.2.1")
set(geneus_MAINTAINER "Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>")
set(geneus_BUILD_DEPENDS "genmsg")
set(geneus_RUN_DEPENDS "genmsg" "python-rospkg")
set(geneus_DEPRECATED "")
set(geneus_BUILDTOOL_DEPENDS "catkin")
set(geneus_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")