#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/odroid/ros_catkin_ws/devel_isolated/common_msgs:$CMAKE_PREFIX_PATH"
export CPATH="/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/include:$CPATH"
export LD_LIBRARY_PATH="/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/lib:/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/cmake_modules/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/genpy/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/genlisp/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/geneus/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/gencpp/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/genmsg/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/catkin/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/install_isolated/lib/arm-linux-gnueabihf:/home/odroid/ros_catkin_ws/devel_isolated/cmake_modules/lib:/home/odroid/ros_catkin_ws/devel_isolated/genpy/lib:/home/odroid/ros_catkin_ws/devel_isolated/genlisp/lib:/home/odroid/ros_catkin_ws/devel_isolated/geneus/lib:/home/odroid/ros_catkin_ws/devel_isolated/gencpp/lib:/home/odroid/ros_catkin_ws/devel_isolated/genmsg/lib:/home/odroid/ros_catkin_ws/devel_isolated/catkin/lib:/home/odroid/ros_catkin_ws/install_isolated/lib"
export PATH="/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/bin:$PATH"
export PKG_CONFIG_PATH="/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/lib/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/cmake_modules/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/genpy/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/genlisp/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/geneus/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/gencpp/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/genmsg/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/catkin/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/install_isolated/lib/arm-linux-gnueabihf/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/cmake_modules/lib/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/genpy/lib/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/genlisp/lib/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/geneus/lib/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/gencpp/lib/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/genmsg/lib/pkgconfig:/home/odroid/ros_catkin_ws/devel_isolated/catkin/lib/pkgconfig:/home/odroid/ros_catkin_ws/install_isolated/lib/pkgconfig"
export PYTHONPATH="/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/lib/python2.7/dist-packages:$PYTHONPATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/odroid/ros_catkin_ws/devel_isolated/common_msgs/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/odroid/ros_catkin_ws/src/common_msgs/common_msgs:$ROS_PACKAGE_PATH"